### ISSUE TITLE
existing photos

### ISSUE THREAD

**Issue by cirrusflyer** [rfgamaral/docker-gphotos-uploader#2]
Will this only upload new photos from the source location?  In other words, if I have a photos folder and keep updating it with new photos, this will only upload the photos that hadn't been uploaded yet?  Or will it attempt to upload every photo in the source folder, even if it had already been uploaded in a past job?

**Comment by rfgamaral** [comment]
I'm not sure, sorry. That's a question for [`gphotos-uploader-cli`](https://github.com/nmrshll/gphotos-uploader-cli), the underlying tool that actually does the uploading work. Please refer to that project for more information on how it works and make a feature requests (if needed). Thanks.

**Comment by cirrusflyer** [comment]
Thanks.  You're right.  And I this seems to be addressed here:

https://github.com/nmrshll/gphotos-uploader-cli/pull/23

Although I can't tell if it's been implemented yet.

**Comment by rfgamaral** [comment]
From my understanding, that only addresses the re-upload issue of already uploaded files (from different albums, for instance), but I could be wrong.

The actual issue - which is the exact same request you made here - is still open: https://github.com/nmrshll/gphotos-uploader-cli/issues/12

You should probably ask there instead of the PR itself :)
